# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 532fa25a699457c73f9d52ee4e34929ee65346d0e74b9e1a4e20c37da193bcccd6a79c5431d748e811c919677599cc057bbde3bbc225d153eb40f0a61d53aaf1

test:
  secret_key_base: 5f982a04d211ad5366694bef997651b8430f88a2b5ff0bf762cca0a5d0310436784482af3a36ececba81d077b635327949c69af2237ff7818d58f9010a387327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
